# Rockchip RK3588 SoC with 4/8/16GB RAM, 16GBB/32GB/64GB/128GB EMMC, m.2 SATA, USB3, USB2, 2xGbE, WIFI6, BT5.1, LCDS, MIPI, eDP, HDMI
BOARD_NAME="TSPi"
BOARD_VENDOR="LCKFB"
BOARDFAMILY="rockchip64"
BOARD_MAINTAINER="JackHuang021"
INTRODUCED="2024"
BOOTCONFIG="imb3588_defconfig"
BOOT_SOC="rk3566"
KERNEL_TARGET="vendor"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3566-lckfb-tspi.dtb"
BOOT_SCENARIO="spl-blobs"
OVERLAY_PREFIX='rk3566'
IMAGE_PARTITION_TABLE="gpt"
BOOT_SUPPORT_SPI="yes"
BOOT_SPI_RKSPI_LOADER="yes"
